version: '2'
services:
  jenkins-master:
    image: odavid/my-bloody-jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - '${PWD}/jenkins-config.yml:/config.yml'
      - '.data/jenkins_home:/var/jenkins_home'
      - '.data/jenkins-workspace-home:/jenkins-workspace-home'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      JAVA_OPTS_MEM: '-Xmx1g'
      JENKINS_ENV_JENKINS_URL: http://${MY_HOST_IP}:8080
      JENKINS_ENV_ADMIN_USER: admin
      JENKINS_ENV_HOST_IP: ${MY_HOST_IP}
      JENKINS_ENV_CONFIG_YML_URL: file:///config.yml
      JENKINS_ENV_QUIET_STARTUP_PERIOD: 120
