security:
  realm: ldap
  server: ldap:389 
  rootDN: dc=example,dc=org
  managerDN: cn=readonly,dc=example,dc=org
  managerPassword: readonly
  userSearchBase: ou=users
  userSearchFilter: uid={0}
  groupSearchBase: ou=groups
  groupSearchFilter: cn={0}
  groupMembershipFilter: member={0}
  displayNameAttr: cn
  emailAttr: mail
  
  permissions:
    jenkins.swarm:
      - hudson.model.Computer.Connect
      - hudson.model.Computer.Disconnect
      - hudson.model.Computer.Configure
      - hudson.model.Computer.Create
      - hudson.model.Computer.Delete
    authenticated: # Special group
      - hudson.model.Hudson.Read
      - hudson.model.Item.Read
      - hudson.model.Item.Discover
    developers:
      - hudson.model.Item.Build
    team-leaders:
      - hudson.model.Item.Build
      - hudson.model.Item.Cancel
      - hudson.model.Item.Configure
    jenkins-admins:
      - hudson.model.Hudson.Administer

tools:
  installations:
    MVN-3.5.0:
      type: maven
      installers:
        - id: '3.5.0'

clouds:
  docker-cloud:
    type: docker
    dockerHostUri: 'unix:///var/run/docker.sock'
    templates:
      - name: generic
        image: odavid/jenkins-jnlp-slave:latest
        labels:
          - generic
        remoteFs: /home/jenkins
        jvmArgs: -Xmx1g
        volumes:
          - '/var/run/docker.sock:/var/run/docker.sock'
        instanceCap: '10'
      - name: cloudbees-tools
        image: cloudbees/jnlp-slave-with-java-build-tools
        remoteFs: /home/jenkins
        jvmArgs: -Xmx1g
        labels:
          - cloudbees-tools

job_dsl_scripts:
  - |
    pipelineJob('nodejs-calc'){
      definition{
        cpsScm{
          lightweight(true)
          scm{
            git{
              remote {
                url('https://github.com/odavid/my-bloody-jenkins.git')
              }
              branches("refs/heads/demo")
            }
            scriptPath('demo/apps/nodejs-calc/Jenkinsfile')
          }
        }
      }
    }